### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by souravbadami** [pixijs/open-games#20]
```
➜  bubbo-bubbo git:(main) ✗ npm start

> bubbo-bubbo@1.0.0 prestart
> run-s assets


> bubbo-bubbo@1.0.0 assets
> assetpack

› Info: Clearing output folder.
› Building: /Users/computer/Documents/workspace/projects/pixijs/open-games/bubbo-bubbo/raw-assets
✔ Plugins Started
✔ Tree Cleaned
✔ Assets Transformed
✔ Assets Post Processed
◐ Tearing Down Plugins...
file:///Users/computer/Documents/workspace/projects/pixijs/open-games/bubbo-bubbo/node_modules/@assetpack/plugin-manifest/dist/es/index.js:42
    const res = val.split('/').filter((v) => v.match(/{m}/) !== null).at(-1);
                                                                      ^

TypeError: val.split(...).filter(...).at is not a function
    at getManifestName (file:///Users/computer/Documents/workspace/projects/pixijs/open-games/bubbo-bubbo/node_modules/@assetpack/plugin-manifest/dist/es/index.js:42:71)
    at collect (file:///Users/computer/Documents/workspace/projects/pixijs/open-games/bubbo-bubbo/node_modules/@assetpack/plugin-manifest/dist/es/index.js:100:24)
    at finish (file:///Users/computer/Documents/workspace/projects/pixijs/open-games/bubbo-bubbo/node_modules/@assetpack/plugin-manifest/dist/es/index.js:74:5)
    at Object.finish (file:///Users/computer/Documents/workspace/projects/pixijs/open-games/bubbo-bubbo/node_modules/@assetpack/plugin-manifest/dist/es/index.js:33:38)
    at Runner.emit (file:///Users/computer/Documents/workspace/projects/pixijs/open-games/bubbo-bubbo/node_modules/@pixi/runner/lib/Runner.mjs:20:21)
    at Processor.run (file:///Users/computer/Documents/workspace/projects/pixijs/open-games/bubbo-bubbo/node_modules/@assetpack/core/dist/es/index.js:438:24)
    at async AssetPack.run (file:///Users/computer/Documents/workspace/projects/pixijs/open-games/bubbo-bubbo/node_modules/@assetpack/core/dist/es/index.js:754:9)
    at async main (file:///Users/computer/Documents/workspace/projects/pixijs/open-games/bubbo-bubbo/node_modules/@assetpack/cli/dist/index.js:61:9)
ERROR: "assets" exited with 1.
```

**OS**: Mac
**Node**: v16.0.0
**NPM**: 7.10.0

**Comment by lijingmt** [comment]
os: centos 9
node v23.9
npm 10.92

met the same issue

**Comment by lijingmt** [comment]
nvm, when I switch to node v18, it works
