### ISSUE TITLE
can't build game

### ISSUE THREAD

**Issue by 1le** [pixijs/open-games#22]
On Windows, running `npm run build` returns:
```
> bubbo-bubbo@1.0.0 clean
> rimraf dist/* public/* .assetpack/*

Error: Illegal characters in path.
    at pathArg (file:///D:/dev/open-games/bubbo-bubbo/node_modules/rimraf/dist/esm/path-arg.js:40:33)
    at file:///D:/dev/open-games/bubbo-bubbo/node_modules/rimraf/dist/esm/index.js:17:54
    at Array.map (<anonymous>)
    at file:///D:/dev/open-games/bubbo-bubbo/node_modules/rimraf/dist/esm/index.js:17:42
    at main (file:///D:/dev/open-games/bubbo-bubbo/node_modules/rimraf/dist/esm/bin.mjs:243:15)
    at file:///D:/dev/open-games/bubbo-bubbo/node_modules/rimraf/dist/esm/bin.mjs:251:5 {
  path: 'D:\\dev\\open-games\\bubbo-bubbo\\dist\\*',
  code: 'EINVAL'
}
ERROR: "clean" exited with 1.
```
tried with node 18 and 20, rifraf 5 and 4.2

**Comment by 1le** [comment]
seems like an issue with rifraf and that it fails when testing `D:\dev\open-games\bubbo-bubbo\dist\*` against `/[*|"<>?:]/`

**Comment by AlphaGamingArcade** [comment]
Any work around? Thanks
